"""add_colunas_loja

Revision ID: 2a73c8a9de12
Revises: 5e553d7dd0a9
Create Date: 2026-05-24 11:32:14.572672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a73c8a9de12'
down_revision: Union[str, Sequence[str], None] = '5e553d7dd0a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lojas', sa.Column('telefone', sa.String(), nullable=True))
    op.add_column('lojas', sa.Column('endereco', sa.String(), nullable=True))
    op.add_column('lojas', sa.Column('email', sa.String(), nullable=True))
    op.add_column('lojas', sa.Column('website', sa.String(), nullable=True))
    op.add_column('lojas', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('lojas', sa.Column('termos_garantia', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lojas', 'termos_garantia')
    op.drop_column('lojas', 'logo_url')
    op.drop_column('lojas', 'website')
    op.drop_column('lojas', 'email')
    op.drop_column('lojas', 'endereco')
    op.drop_column('lojas', 'telefone')
    # ### end Alembic commands ###
