"""add_is_servico

Revision ID: 5e553d7dd0a9
Revises: fd95c3c9e362
Create Date: 2026-05-17 19:04:52.325445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e553d7dd0a9'
down_revision: Union[str, Sequence[str], None] = 'fd95c3c9e362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('is_servico', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'is_servico')
    # ### end Alembic commands ###
