"""Add_indexes_for_performance

Revision ID: 9fd817c07f0d
Revises: 2a73c8a9de12
Create Date: 2026-06-14 21:46:09.121406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd817c07f0d'
down_revision: Union[str, Sequence[str], None] = '2a73c8a9de12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_clientes_cpf'), 'clientes', ['cpf'], unique=False)
    op.create_index(op.f('ix_clientes_loja_id'), 'clientes', ['loja_id'], unique=False)
    op.create_index(op.f('ix_clientes_telefone'), 'clientes', ['telefone'], unique=False)
    op.create_index(op.f('ix_itens_os_os_id'), 'itens_os', ['os_id'], unique=False)
    op.create_index(op.f('ix_itens_os_produto_id'), 'itens_os', ['produto_id'], unique=False)
    op.create_index(op.f('ix_itens_venda_produto_id'), 'itens_venda', ['produto_id'], unique=False)
    op.create_index(op.f('ix_itens_venda_venda_id'), 'itens_venda', ['venda_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_estoque_produto_id'), 'movimentacoes_estoque', ['produto_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_estoque_usuario_id'), 'movimentacoes_estoque', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_ordens_servico_atendente_id'), 'ordens_servico', ['atendente_id'], unique=False)
    op.create_index(op.f('ix_ordens_servico_cliente_id'), 'ordens_servico', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_ordens_servico_data_entrada'), 'ordens_servico', ['data_entrada'], unique=False)
    op.create_index(op.f('ix_ordens_servico_loja_id'), 'ordens_servico', ['loja_id'], unique=False)
    op.create_index(op.f('ix_ordens_servico_status'), 'ordens_servico', ['status'], unique=False)
    op.create_index(op.f('ix_ordens_servico_tecnico_id'), 'ordens_servico', ['tecnico_id'], unique=False)
    op.create_index(op.f('ix_ordens_servico_usuario_id'), 'ordens_servico', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_produtos_categoria'), 'produtos', ['categoria'], unique=False)
    op.create_index(op.f('ix_produtos_loja_id'), 'produtos', ['loja_id'], unique=False)
    op.create_index(op.f('ix_solicitacoes_compra_loja_id'), 'solicitacoes_compra', ['loja_id'], unique=False)
    op.create_index(op.f('ix_solicitacoes_compra_os_id'), 'solicitacoes_compra', ['os_id'], unique=False)
    op.create_index(op.f('ix_solicitacoes_compra_status'), 'solicitacoes_compra', ['status'], unique=False)
    op.create_index(op.f('ix_transacoes_financeiras_data_transacao'), 'transacoes_financeiras', ['data_transacao'], unique=False)
    op.create_index(op.f('ix_transacoes_financeiras_loja_id'), 'transacoes_financeiras', ['loja_id'], unique=False)
    op.create_index(op.f('ix_transacoes_financeiras_ordem_servico_id'), 'transacoes_financeiras', ['ordem_servico_id'], unique=False)
    op.create_index(op.f('ix_transacoes_financeiras_usuario_id'), 'transacoes_financeiras', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_usuarios_loja_id'), 'usuarios', ['loja_id'], unique=False)
    op.create_index(op.f('ix_vendas_cliente_id'), 'vendas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_vendas_data_venda'), 'vendas', ['data_venda'], unique=False)
    op.create_index(op.f('ix_vendas_loja_id'), 'vendas', ['loja_id'], unique=False)
    op.create_index(op.f('ix_vendas_os_id'), 'vendas', ['os_id'], unique=False)
    op.create_index(op.f('ix_vendas_usuario_id'), 'vendas', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendas_usuario_id'), table_name='vendas')
    op.drop_index(op.f('ix_vendas_os_id'), table_name='vendas')
    op.drop_index(op.f('ix_vendas_loja_id'), table_name='vendas')
    op.drop_index(op.f('ix_vendas_data_venda'), table_name='vendas')
    op.drop_index(op.f('ix_vendas_cliente_id'), table_name='vendas')
    op.drop_index(op.f('ix_usuarios_loja_id'), table_name='usuarios')
    op.drop_index(op.f('ix_transacoes_financeiras_usuario_id'), table_name='transacoes_financeiras')
    op.drop_index(op.f('ix_transacoes_financeiras_ordem_servico_id'), table_name='transacoes_financeiras')
    op.drop_index(op.f('ix_transacoes_financeiras_loja_id'), table_name='transacoes_financeiras')
    op.drop_index(op.f('ix_transacoes_financeiras_data_transacao'), table_name='transacoes_financeiras')
    op.drop_index(op.f('ix_solicitacoes_compra_status'), table_name='solicitacoes_compra')
    op.drop_index(op.f('ix_solicitacoes_compra_os_id'), table_name='solicitacoes_compra')
    op.drop_index(op.f('ix_solicitacoes_compra_loja_id'), table_name='solicitacoes_compra')
    op.drop_index(op.f('ix_produtos_loja_id'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_categoria'), table_name='produtos')
    op.drop_index(op.f('ix_ordens_servico_usuario_id'), table_name='ordens_servico')
    op.drop_index(op.f('ix_ordens_servico_tecnico_id'), table_name='ordens_servico')
    op.drop_index(op.f('ix_ordens_servico_status'), table_name='ordens_servico')
    op.drop_index(op.f('ix_ordens_servico_loja_id'), table_name='ordens_servico')
    op.drop_index(op.f('ix_ordens_servico_data_entrada'), table_name='ordens_servico')
    op.drop_index(op.f('ix_ordens_servico_cliente_id'), table_name='ordens_servico')
    op.drop_index(op.f('ix_ordens_servico_atendente_id'), table_name='ordens_servico')
    op.drop_index(op.f('ix_movimentacoes_estoque_usuario_id'), table_name='movimentacoes_estoque')
    op.drop_index(op.f('ix_movimentacoes_estoque_produto_id'), table_name='movimentacoes_estoque')
    op.drop_index(op.f('ix_itens_venda_venda_id'), table_name='itens_venda')
    op.drop_index(op.f('ix_itens_venda_produto_id'), table_name='itens_venda')
    op.drop_index(op.f('ix_itens_os_produto_id'), table_name='itens_os')
    op.drop_index(op.f('ix_itens_os_os_id'), table_name='itens_os')
    op.drop_index(op.f('ix_clientes_telefone'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_loja_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_cpf'), table_name='clientes')
    # ### end Alembic commands ###
