"""baseline_atual

Revision ID: fd95c3c9e362
Revises: 
Create Date: 2026-05-10 17:58:16.663406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd95c3c9e362'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('itens_os', 'os_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('itens_os', 'produto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('itens_os', 'nome_produto',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_itens_os_id'), 'itens_os', ['id'], unique=False)
    op.drop_column('itens_os', 'criado_at')
    op.alter_column('itens_venda', 'quantidade',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('itens_venda', 'preco_unitario',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)
    op.alter_column('itens_venda', 'venda_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('itens_venda', 'produto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('fk_item_venda'), 'itens_venda', type_='foreignkey')
    op.create_foreign_key(None, 'itens_venda', 'vendas', ['venda_id'], ['id'])
    op.alter_column('ordens_servico', 'marca',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ordens_servico', 'modelo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ordens_servico', 'defeito',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('ordens_servico', 'observacoes_balcao',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('ordens_servico', 'laudo_tecnico',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('ordens_servico', 'pecas_necessarias',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('ordens_servico', 'valor_orcamento',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('ordens_servico', 'valor_mao_de_obra',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('ordens_servico', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ordens_servico', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ordens_servico', 'loja_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('ordens_servico', 'aparelho')
    op.alter_column('produtos', 'preco_custo',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('solicitacoes_compra', 'loja_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'transacoes_financeiras', 'ordens_servico', ['ordem_servico_id'], ['id'])
    op.alter_column('usuarios', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuarios', 'senha_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuarios', 'cargo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuarios', 'loja_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vendas', 'valor_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)
    op.alter_column('vendas', 'forma_pagamento',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vendas', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vendas', 'loja_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('vendas_os_id_fkey'), 'vendas', type_='foreignkey')
    op.drop_constraint(op.f('vendas_vendedor_id_fkey'), 'vendas', type_='foreignkey')
    op.create_foreign_key(None, 'vendas', 'ordens_servico', ['os_id'], ['id'])
    op.drop_column('vendas', 'vendedor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendas', sa.Column('vendedor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vendas', type_='foreignkey')
    op.create_foreign_key(op.f('vendas_vendedor_id_fkey'), 'vendas', 'usuarios', ['vendedor_id'], ['id'])
    op.create_foreign_key(op.f('vendas_os_id_fkey'), 'vendas', 'ordens_servico', ['os_id'], ['id'], ondelete='SET NULL')
    op.alter_column('vendas', 'loja_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vendas', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vendas', 'forma_pagamento',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vendas', 'valor_total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('usuarios', 'loja_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usuarios', 'cargo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuarios', 'senha_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuarios', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'transacoes_financeiras', type_='foreignkey')
    op.alter_column('solicitacoes_compra', 'loja_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('produtos', 'preco_custo',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.add_column('ordens_servico', sa.Column('aparelho', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('ordens_servico', 'loja_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ordens_servico', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ordens_servico', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ordens_servico', 'valor_mao_de_obra',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('ordens_servico', 'valor_orcamento',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('ordens_servico', 'pecas_necessarias',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('ordens_servico', 'laudo_tecnico',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('ordens_servico', 'observacoes_balcao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('ordens_servico', 'defeito',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('ordens_servico', 'modelo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ordens_servico', 'marca',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'itens_venda', type_='foreignkey')
    op.create_foreign_key(op.f('fk_item_venda'), 'itens_venda', 'vendas', ['venda_id'], ['id'], ondelete='CASCADE')
    op.alter_column('itens_venda', 'produto_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('itens_venda', 'venda_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('itens_venda', 'preco_unitario',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('itens_venda', 'quantidade',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('itens_os', sa.Column('criado_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_itens_os_id'), table_name='itens_os')
    op.alter_column('itens_os', 'nome_produto',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('itens_os', 'produto_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('itens_os', 'os_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
